// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Printer is an autogenerated mock type for the Printer type
type Printer struct {
	mock.Mock
}

// Print provides a mock function with given fields:
func (_m *Printer) Print() {
	_m.Called()
}
